// Bilingual content for NC Studio — Nacho Cabrera
window.NC_CONTENT = {
  es: {
    nav: {
      about: "Sobre mí",
      work: "Trabajos",
      services: "Servicios",
      pricing: "Precios",
      contact: "Contacto",
      cta: "Iniciar proyecto",
    },
    hero: {
      status: "Disponible — Q3 2026",
      headlineA: "Páginas web ",
      headlineB: "modernas",
      headlineC: ", hechas a medida.",
      sub: "Soy Ignacio Cabrera. Diseñador y programador de páginas web.",
      ctaPrimary: "Iniciar un proyecto",
      ctaGhost: "Ver trabajos",
    },
    about: {
      eyebrow: "01 — Sobre mí",
      title: "Soy Ignacio Cabrera, diseñador y programador de páginas web.",
      bodyA: "Diseño y programo sitios rápidos, claros y pensados para convertir. Trabajo con marcas que recién empiezan y con negocios que necesitan renovar su presencia online.",
      bodyB: "Cada proyecto empieza con una conversación corta y termina con un sitio que tu cliente entiende en segundos.",
    },
    services: {
      eyebrow: "02 — Servicios",
      title: "Qué hago.",
      items: [
        { n: "01", t: "Diseño", d: "Diseño visual a medida — tipografía, color, layout y prototipo navegable antes de tocar código." },
        { n: "02", t: "Código", d: "Desarrollo limpio y rápido. Sitios estáticos y SPAs optimizados para performance, SEO y carga." },
        { n: "03", t: "Mantenimiento", d: "Actualizaciones, copys nuevos, secciones extra, monitoreo de uptime y soporte continuo." },
      ],
    },
    work: {
      eyebrow: "03 — Trabajos",
      title: "Páginas web que puedo hacerte.",
      placeholderTag: "EN VIVO",
      placeholderTagSoon: "PRÓXIMAMENTE",
      cta: "Ver caso",
      visit: "Visitar sitio",
      projects: [
        {
          name: "El Diez Baires",
          cat: "Comercio",
          year: "2026",
          url: "https://el-diez-baires-production.up.railway.app/",
          live: true,
          desc: "Sitio en producción para El Diez Baires — diseño, desarrollo y deploy completos.",
          tags: ["React", "Tailwind", "Railway"],
        },
        { name: "Lumen Café", cat: "Comercio local", year: "2026", desc: "Sitio institucional con menú dinámico y reservas online para una cafetería de especialidad.", tags: ["React", "Tailwind", "Sanity"] },
        { name: "Atelier Reyes", cat: "Portfolio", year: "2026", desc: "Portafolio de arquitectura con galería en grid masonry y modo lectura.", tags: ["Next.js", "MDX", "Vercel"] },
        { name: "Norte Legal", cat: "Estudio profesional", year: "2025", desc: "Sitio para estudio jurídico con formulario de consulta y blog de actualidad.", tags: ["Astro", "Tailwind"] },
        { name: "Bloom Pilates", cat: "Servicio local", year: "2025", desc: "Web con turnero integrado, planes y testimonios de alumnos.", tags: ["React", "Calendly"] },
        { name: "Vértice 360", cat: "Inmobiliaria", year: "2024", desc: "Catálogo de propiedades con filtros, mapa y formulario de contacto por propiedad.", tags: ["Next.js", "Mapbox"] },
      ],
    },
    pricing: {
      eyebrow: "04 — Precios",
      title: "Dos formas de trabajar.",
      sub: "Elegí el modelo que mejor encaje con tu negocio. Sin contratos largos.",
      monthly: {
        tag: "Recomendado",
        name: "Plan Mensual",
        price: "ARS / mes",
        pricesub: "valor a definir según alcance",
        desc: "Para marcas que necesitan una web viva: cambios frecuentes, novedades, campañas.",
        feats: ["Mantenimiento e infraestructura", "Actualizaciones ilimitadas menores", "Soporte prioritario por WhatsApp", "Reportes de performance mensuales", "Backups y monitoreo de uptime"],
        cta: "Hablar de mantenimiento",
      },
      flexible: {
        tag: "Pay-as-you-go",
        name: "Plan Flexible",
        price: "Por proyecto",
        pricesub: "pagás solo cuando lo necesitás",
        desc: "Para sitios que ya están en marcha y solo requieren cambios puntuales.",
        feats: ["Pago por hora o por entregable", "Cambios bajo demanda", "Sin compromiso mensual", "Presupuesto antes de empezar", "Tiempo de respuesta: 48hs"],
        cta: "Pedir presupuesto",
      },
    },
    contact: {
      eyebrow: "05 — Contacto",
      title: "Contame qué tenés en mente.",
      sub: "Respondo el mismo día hábil. Sin formularios eternos.",
      name: "Nombre",
      email: "Email",
      type: "Tipo de proyecto",
      typeOpts: ["Landing page", "Portfolio", "Sitio institucional", "Otro"],
      msg: "Sobre qué se trata",
      msgPh: "Contame brevemente qué necesitás, plazo, referencias…",
      send: "Enviar mensaje",
      sending: "Enviando…",
      sent: "Mensaje enviado",
      sentSub: "Te respondo en menos de 24hs.",
      direct: "O escribime directo",
      namePh: "Ignacio Cabrera",
    },
    footer: {
      line: "Diseñado y construido por Ignacio Cabrera · NC Studio",
      based: "Argentina · Trabajo remoto a todo el mundo",
      rights: "Todos los derechos reservados",
    },
  },
  en: {
    nav: {
      about: "About",
      work: "Work",
      services: "Services",
      pricing: "Pricing",
      contact: "Contact",
      cta: "Start a project",
    },
    hero: {
      status: "Available — Q3 2026",
      headlineA: "Modern ",
      headlineB: "websites",
      headlineC: ", built from scratch.",
      sub: "I'm Ignacio Cabrera. Web designer and developer.",
      ctaPrimary: "Start a project",
      ctaGhost: "See work",
    },
    about: {
      eyebrow: "01 — About",
      title: "I'm Ignacio Cabrera, web designer and developer.",
      bodyA: "I design and build fast, clear sites that convert. I work with brands just getting started and with businesses ready to refresh their online presence.",
      bodyB: "Every project starts with a short conversation and ends with a site your customer understands in seconds.",
    },
    services: {
      eyebrow: "02 — Services",
      title: "What I do.",
      items: [
        { n: "01", t: "Design", d: "Custom visual design — type, color, layout and interactive prototype before any code." },
        { n: "02", t: "Code", d: "Clean, fast development. Static sites and SPAs optimized for performance, SEO and load." },
        { n: "03", t: "Maintenance", d: "Updates, new copy, extra sections, uptime monitoring and ongoing support." },
      ],
    },
    work: {
      eyebrow: "03 — Work",
      title: "Websites I can build for you.",
      placeholderTag: "LIVE",
      placeholderTagSoon: "COMING SOON",
      cta: "Read case",
      visit: "Visit site",
      projects: [
        {
          name: "El Diez Baires",
          cat: "Business",
          year: "2026",
          url: "https://el-diez-baires-production.up.railway.app/",
          live: true,
          desc: "Live site for El Diez Baires — full design, development and deploy.",
          tags: ["React", "Tailwind", "Railway"],
        },
        { name: "Lumen Café", cat: "Local business", year: "2026", desc: "Brand site with dynamic menu and online reservations for a specialty coffee shop.", tags: ["React", "Tailwind", "Sanity"] },
        { name: "Atelier Reyes", cat: "Portfolio", year: "2026", desc: "Architecture portfolio with masonry gallery and reading mode.", tags: ["Next.js", "MDX", "Vercel"] },
        { name: "Norte Legal", cat: "Pro services", year: "2025", desc: "Site for a law firm with consultation form and news blog.", tags: ["Astro", "Tailwind"] },
        { name: "Bloom Pilates", cat: "Local service", year: "2025", desc: "Site with booking, plans and student testimonials.", tags: ["React", "Calendly"] },
        { name: "Vértice 360", cat: "Real estate", year: "2024", desc: "Property catalog with filters, map and per-property contact form.", tags: ["Next.js", "Mapbox"] },
      ],
    },
    pricing: {
      eyebrow: "04 — Pricing",
      title: "Two ways to work together.",
      sub: "Pick the model that fits your business. No long contracts.",
      monthly: {
        tag: "Recommended",
        name: "Monthly Plan",
        price: "USD / mo",
        pricesub: "scoped to your project",
        desc: "For brands that need a living site: frequent changes, news, campaigns.",
        feats: ["Hosting and maintenance", "Unlimited minor updates", "Priority support over WhatsApp", "Monthly performance reports", "Backups and uptime monitoring"],
        cta: "Talk maintenance",
      },
      flexible: {
        tag: "Pay-as-you-go",
        name: "Flexible Plan",
        price: "Per project",
        pricesub: "pay only when you need it",
        desc: "For sites already up and running that only need occasional changes.",
        feats: ["Hourly or per-deliverable", "Changes on demand", "No monthly commitment", "Quote before we start", "Reply time: 48h"],
        cta: "Request a quote",
      },
    },
    contact: {
      eyebrow: "05 — Contact",
      title: "Tell me what you have in mind.",
      sub: "I reply the same business day. No endless forms.",
      name: "Name",
      email: "Email",
      type: "Project type",
      typeOpts: ["Landing page", "Portfolio", "Brand site", "Other"],
      msg: "What's it about",
      msgPh: "Briefly tell me what you need, timeline, references…",
      send: "Send message",
      sending: "Sending…",
      sent: "Message sent",
      sentSub: "I'll reply within 24h.",
      direct: "Or reach me directly",
      namePh: "Ignacio Cabrera",
    },
    footer: {
      line: "Designed and built by Ignacio Cabrera · NC Studio",
      based: "Argentina · Remote worldwide",
      rights: "All rights reserved",
    },
  },
};
